#!/bin/bash
if [ -d "${v_contribBase}"/tpoder/dstat/data ]; then
  rm -rf "${v_contribBase}"/tpoder/dstat/data
  mkdir -p "${v_contribBase}"/tpoder/dstat/data
else
  mkdir -p "${v_contribBase}"/tpoder/dstat/data
fi
git clone https://github.com/tanelpoder/dstat.git "${v_contribBase}"/tpoder/dstat/data
